language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install

script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then npm run generate:gh-pages; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run generate; fi

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
    repo: NetAcademia/netacademia.github.io
    target-branch: master
    local-dir: dist
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
    target-branch: gh-pages
    local-dir: dist-ghpages
    on:
      branch: develop

