version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    branches:
      only:
        - DEV-244
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: npm install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: generate dist
          command: |
            if [ $CIRCLE_BRANCH == "DEV-244" ]; then
              npm run generate:test
            elif [ $CIRCLE_BRANCH == "master" ]; then
              npm run generate:prod
            fi
      - run:
          name: deploy to gh pages
          command: |
            if [ $CIRCLE_BRANCH == "DEV-244" ]; then
              npm run deploy:test
            elif [ $CIRCLE_BRANCH == "master" ]; then
              npm run deploy:prod
            fi
