version: 2
jobs:
  build:
    branches:
      only:
        - DEV-244
    working_directory: ~/repo
    docker:
      - image: circleci/node:8:11
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - "node_modules"
       - run:
           name: Build
           command: yarn run generte:test
